
"""Compatibility layer that mirrors the legacy `model_features` module inside the package."""

from .entity import extract_entity_names, namedEntityRecog, ner
from .rbm import RBM, load_data, test_rbm
from .summary import executeForAFile
from .text_features import (
    centroidSimilarity,
    get_cosine,
    is_number,
    numericToken,
    posTagger,
    properNounScores,
    remove_stop_words,
    sentenceLength,
    sentencePos,
    similar,
    similarityScores,
    split_into_sentences,
    text_to_vector,
    tfIsf,
    thematicFeature,
)
from .resources import (
    WORD,
    acronyms,
    caps,
    cwd,
    porter,
    prefixes,
    sentenceLengths,
    starters,
    stemmer,
    stop,
    suffixes,
    websites,
)

__all__ = [
    'RBM',
    'load_data',
    'test_rbm',
    'extract_entity_names',
    'ner',
    'namedEntityRecog',
    'split_into_sentences',
    'remove_stop_words',
    'posTagger',
    'tfIsf',
    'similar',
    'similarityScores',
    'properNounScores',
    'text_to_vector',
    'get_cosine',
    'centroidSimilarity',
    'is_number',
    'numericToken',
    'sentencePos',
    'sentenceLength',
    'thematicFeature',
    'executeForAFile',
    'porter',
    'stemmer',
    'WORD',
    'caps',
    'prefixes',
    'suffixes',
    'starters',
    'acronyms',
    'websites',
    'stop',
    'sentenceLengths',
    'cwd',
]
